### ISSUE TITLE
Add support for SQL databases

### ISSUE THREAD

**Issue by nodegin** [reactGo/reactGo#121]
Will you build a branch for mysql / mariadb databases?
Although there's another reap repository, but since most logic should same
and the reap seems not actively maintained
How about make a branch to adding support for the MySQL / MariaDB databases
Thanks

**Comment by choonkending** [comment]
@nodegin Good idea! If you wanted, you could also submit a PR and I'd be happy to review it as well!

**Comment by mjewell** [comment]
I also thought this would be useful so I've started working on it. Take a look here if you're interested:

https://github.com/mjewell/react-webpack-node/tree/feature/postgres

**Comment by choonkending** [comment]
@mjewell Thanks very much for that! I actually had a repo called https://github.com/choonkending/reap which had an example for postgres (this was based off an old branch which used alt).

Definitely worth creating a PR for a branch in this repo because it's more up to date with redux.

Unrelated to this issue but ...
I'd like to think about how we could make this repository database agnostic. (Yeoman generator by @iiegor perhaps). We should also make it easy to remove database dependencies entirely if a user does not want a db for hackday (like I did).

The options are:
- Yeoman 
- Branch for each DB (hard to maintain but because of how frequently we update)
- Separate repo for each DB

**Comment by mjewell** [comment]
Yeah, I saw reap and initially used it as a reference, but it's out of date enough that now I'm mostly ignoring it.

And yeah, totally agree, that would be great. I was hoping that once I get this working with postgres I can make it so that it's easy to swap out for the different databases sequelize supports, but that's still more limited than I'd like

**Comment by choonkending** [comment]
> I was hoping that once I get this working with postgres I can make it so that it's easy to swap out for the different databases sequelize supports, but that's still more limited than I'd like

I say go for it!! Let me know if you need help! :smile:

**Comment by mjewell** [comment]
#187

**Comment by GGAlanSmithee** [comment]
Fixed in  #193
