### ISSUE TITLE
Using classes from 3rd party libraries inside components

### ISSUE THREAD

**Issue by IljaDaderko** [reactGo/reactGo#224]
I came across an issue trying to use [Flexbox grid](http://flexboxgrid.com/) in my project. What I did is make a new folder named `libraries` inside `app/css` and put grid css file in there, afterwards, inside `main.css` I included it like so `@import './libraries/grid.css'` assuming that these classes will now be available across the project as `main.css` is included inside `App.jsx` , however using them like so:

```
// This is just a random component from my components folder that is included inside HomePage container
import React from 'react'
import { IndexLink, Link } from 'react-router'
import classNames from 'classnames/bind'
import styles from './Header.css'

const cx = classNames.bind(styles)

export default class Header extends React.Component {
  render () {
    return (
      <header className={cx('Header', 'row', 'center-xs')}>
      ...
      </header>
    )
  }
}

```

It seems like styles from `Header.css` are including fine, as inside markup the `.Header` class is displaying fine (Something like: `Header__Header___1j2Yj`), but `row` and `center-xs` don't seem to work unless I actually copy whole code from `grid.css` inside `Header.css` which probably means that I am not including it correctly, hence the question how would I make classes like `row`, `col-` etc.. from `grid.css` available to all of my components.

**Comment by choonkending** [comment]
Hey thanks for raising this issue. 

There should be a better way to use both libraries and our own css.

Because we're using `css?modules` in our `webpack.config`, `className` changes to being prefixed, unless you specify in your css to have

```css
:global {
  .row-something-something {

   }
}
```

so you would be able include those classnames. Let me know how that goes!

**Comment by huntwj** [comment]
@choonkending Would you be so kind as to elaborate on this answer? Perhaps I'm just tired, but I'm having trouble understanding what you're getting at.

1) If I want to use vanilla flexbox-grid, then how do I include that in my app in such a way that the classes are not namespaced, either in the DOM or in the CSS file itself? I would prefer to be able to include the flexbox-grid CSS somewhere in my project without modification.

2) It seems like it *should* be a simple process to just use react-flexbox-grid, but the webpack config changes are stumping me. (Surprise surprise, I'm not a webpack expert. :/ )

Perhaps this belongs in another issue ticket, but it would be great if we could add instructions for doing both of these in the reactGo documentation.

(Or does reactGo have another suggested solution for handling grid/layout issues?)

**Comment by slavab89** [comment]
We're cleaning up issues on the project and since this is an old issue we're closing it.
If you still experience this or have an issue, please comment here or open a new one.
`flexbox-grid` has also changed a few things on their latest version including their build process so it might solve the original issue that was here.
