### ISSUE TITLE
How to use npm distributed css?

### ISSUE THREAD

**Issue by darkyen** [reactGo/reactGo#235]
Hey guys, I am using `react-mdl` for the UI lib and they distribute their own updated css files for mdl. Usually I'd just do import 'react-mdl/extra/material.css'; but due to postcss loader I do not think that is the right way to do things. 

How should I import the 3rd party css in this scenario?

**Comment by jrodl3r** [comment]
Might be a little more complex then just loading the CSS file. Wouldn't `classNames` (cx) also break the class naming structure that MDL uses/expects? I'm not 100% sure, but seems like a pretty significant conversion of MDL would be needed.

**Comment by darkyen** [comment]
Which is why am asking here :P

**Comment by psimyn** [comment]
I think importing it globally should be fine - you can use `:global` in css for class names that you don't want transformed. Transforming the mdl- classes would mean changing react-mdl

**Comment by caranicas** [comment]
@psimyn do you think you could outline that in the read me. I got stuck on this a long time ago and got it working by just ripping out the hash that was getting appended  to all my class names.  This obviously removed some of the benefit but it wasn't a benefit that I was really making use of so I didn't care at the time.  But moving forward I would like to know how to include external component lobs properly and get their base css to work.

**Comment by nicholasstephan** [comment]
Did you figure this out? I'm running into the same problem including any component that has some css that needs to be included.

**Comment by slavab89** [comment]
We're cleaning up issues on the project and since this is an old issue we're closing it. Moreover, the code has changed quite a lot since this issue was opened.
If you still experience this or have an issue, please comment here or open a new one

The general idea is to include the css in the final build. You should be able to just add `include '....css'` in `client.jsx`. It might also be possible that you will have to disable the css loader for the library.
