### ISSUE TITLE
Preform api call through the server from action?

### ISSUE THREAD

**Issue by IljaDaderko** [reactGo/reactGo#284]
I ran into a CORS issue today while using axios inside my action alongside mailchimp api. This also led me to think about something else.

If I want to perform an api call, like a post or delete, I do it from my actions, where I need to define my api url. Due to this it is exposed to everyone else. I think this is not the case when we use static need middleware? Hence, I wanted to ask you if it is possible to extend this project to something like, hitting `/app/` endpoint in actions will result in triggering middleware that has private api path defined there?

**Comment by slavab89** [comment]
We're cleaning up issues on the project and since this is an old issue we're closing it. Moreover, the code has changed quite a lot since this issue was opened.
If you still experience this or have an issue, please comment here or open a new one

Regarding your question. You can use `axios` to send an API call to the server by just defining the route, for example, just use `/api/topics` and it will send the request to the server side where you can have some middleware that handles this. If you need to send the api call to a different server then you will have to explicitly define the whole url endpoint, in which case the destination server would have to support CORS
