### ISSUE TITLE
Openshift deployment?

### ISSUE THREAD

**Issue by IzaGz** [reactGo/reactGo#308]
Does anybody have openshift deployment strategy?

**Comment by choonkending** [comment]
@IzaGz Not at the moment :) Would you like to add a PR for that?

**Comment by ZeroCho** [comment]
I'm trying now... tell you guys after done.

**Comment by IzaGz** [comment]
So, @ZeroCho, how's it going?

**Comment by slavab89** [comment]
We're cleaning up issues on the project and since this is an old issue we're closing it.
If you still experience this or have an issue, please comment here or open a new one.

In case you're speaking about dockerizing the project then please check https://github.com/reactGo/reactGo/issues/631 for an example.
