### ISSUE TITLE
Cookies not present in req.header inside server.jsx on initial load

### ISSUE THREAD

**Issue by IljaDaderko** [reactGo/reactGo#313]
I noticed that cookies are not present in `req.headers` on initial page load, however after refresh everything is is fine and they are indeed there. This is an issue when we, for example, setu authenticated value inside users store based on cookie.

You can view this by adding simple console.log that returns headers in terminal when we load a page:

```
export default function render (req, res) {
  console.log(req.headers)
  ...
```

EDIT: I believe this could be caused by `siteOnly: strict` cookies

**Comment by slavab89** [comment]
We're cleaning up issues on the project and since this is an old issue we're closing it. Moreover, the code has changed quite a lot since this issue was opened.
If you still experience this or have an issue, please comment here or open a new one.

Regarding this issue, please elaborate at which point of the initial load there are no cookies. In case you're referring to an api that's being made during the initial load then yes, there wont be cookies in that external request since we dont pass them. On other cases, the middleware on the server side that handles the generation of the final HTML should have cookies defined.
