### ISSUE TITLE
@decorator function to compose classes

### ISSUE THREAD

**Issue by tsm91** [reactGo/reactGo#32]
Hi @choonkending, when i use a decorator function on a react class i get the following console.warn:

``` js
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) 3">WebRTC</a></nav><div data-reactid=".v
 (server) 3">WebRTC</a></nav><h1 data-reactid=".vt
```

here is the example decorator

``` js
function withWebRTC(ComposedComponent) {
  return class WebRTC extends React.Component {
    constructor() {
      super();
      this.state = {
        whatever: true
      };
    }
    render() {
      return (
        <ComposedComponent {...this.props} whatever ={this.state. whatever} />
      );
    }
  };
}
```

The code is working properly but i guess it wouldn't be always the case.

**Comment by choonkending** [comment]
@tsm91 Yea, this occurs when the server rendered template returned is not the same as what the client expected. 

If you are using the `UniversalRenderer` function, you might need to bootstrap the store in the store in [routes.js](https://github.com/choonkending/react-webpack-node/blob/master/server/config/routes.js#L69), instead of initialising the state like this ```this.state = {
        whatever: true
      };```

Also I noticed that the client has `<div>` after your '</nav>', whereas your server has `<h1>` after `</nav>'. 

If you have a branch somewhere, I could have a look at it when I have the time.

Btw, WebRTC :)

**Comment by caranicas** [comment]
Im not sure this is related to decorators. I've gotten that warning a couple of times, I think if you update your jsx too much the server and client get out of sync. Anytime i see that a clean and a build fix me right up.

**Comment by NeXTs** [comment]
I got this message on every change at any jsx file

this weird trick helped me to get rid of that annoying message
http://stackoverflow.com/a/33521172/1221082

**Comment by GGAlanSmithee** [comment]
Closing this issue, as it's been quite for a long time, and the code had changed a lot since. If this problem resurfaces, please create a new issue.
