### ISSUE TITLE
Unable to Debug Node Server 

### ISSUE THREAD

**Issue by jonrose182** [reactGo/reactGo#350]
I've been trying to setup debugging on the Node server through WebStorm. I've tried both remote and local debugging. I am able to connect to the remote debug port, but none of the breakpoints hit. Has anyone been able to debug the server with this stack?

**Comment by ZeroCho** [comment]
I've used Webstorm and it's very hard to debug Webpack with webstorm

**Comment by rbrugnollo** [comment]
Have you guys tried vscode? I couldn't get it working there...

**Comment by slavab89** [comment]
We're cleaning up issues on the project and since this is an old issue we're closing it.
If you still experience this or have an issue, please comment here or open a new one.

Live previously said, its pretty hard to debug webpack/babel generated code. I believe that your best option is to use `console.log` statements or change your whole server to be regular node and transpile only the client side code.
Moreover, please check [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000138204-Debugging-webpack-dev-server-application) [here](https://blog.jetbrains.com/webstorm/2017/01/debugging-react-apps/) [here](https://dev4devs.com/2017/01/17/js-how-to-debug-your-nodejs-webpack-application-in-intellij-ide-or-webstorm/). Those are just results from google, didnt try it myself.
