### ISSUE TITLE
Offline Support

### ISSUE THREAD

**Issue by psimyn** [reactGo/reactGo#361]
Service worker time
## Enhancement

Add offline support
- When offline, show app shell (show nav and loader) - https://developers.google.com/web/updates/2015/11/app-shell?hl=en
- Cache previous content, then fetch new items when connected
- [x] Add https for dev
- [x] Add service worker / serve from `/`
- [ ] Static template
- [ ] File caching

**Comment by caranicas** [comment]
@psimyn im not sure what you mean by

> Basic app shell (show nav and loader)

could you go into a bit more detail?

**Comment by jrodl3r** [comment]
@psimyn you can achieve this by building out your UI and components using that style architecture. _ex:_ style your panels to display w/ background-image spinner-gif's, or a placeholder-message (etc) until your fetched-data.length is > 0 👍)

**Comment by choonkending** [comment]
Might be worth adding 
- [ ] manifest.json

**Comment by jrodl3r** [comment]
what about this...? https://github.com/lettertwo/appcache-webpack-plugin

**Comment by caranicas** [comment]
@jrodl3r here is the [clip](https://www.youtube.com/watch?v=cmGr0RszHc8&t=8m20s) from the video I posted where he warns against using app cache.

**Comment by psimyn** [comment]
and the article where he talks about it http://alistapart.com/article/application-cache-is-a-douchebag

**Comment by jrodl3r** [comment]
eek. sorry.. just randomly shared...

**Comment by mhlavacka** [comment]
Long-term cache is a huge issue for us, not have to update file versions on every new deployment.  I'm on this for two days already and can't figure it out due to my limited Webpack knowledge. Same as in https://github.com/reactGo/reactGo/issues/282, I successfully generate `assets.json`. Currently, I'm using https://gist.github.com/mhlavacka/ac348ac6fa139491bb5b1b92c4e8cca9 to rewrite file names directly in the files, but then there are different filenames on the server and on the browser what results in 404 error.
