### ISSUE TITLE
Server side code unit tests

### ISSUE THREAD

**Issue by karkkant** [reactGo/reactGo#410]
Would it be possible to move unit tests from under "/app" to root, and include configurations to allow server side code tests? Most of the critical code I want to test is on server side, and "/app/tests" feels like a wrong place for it. 

Also, I tried to add unit tests targeting server code, but the includes threw errors. Couldn't figure out a proper way to configure karma to make it work.

**Comment by slavab89** [comment]
We're cleaning the project of stale issues therefore i'm closing this. If you still have any issue, please comment here or open a new issue.

You can have several test folders if you like, for client and server-side. I'm assuming that you want to test the different middlewares that the server side has.
Regarding the `include` and other ES6 things, you probably need to define mocha to work alongside the webpack configuration so that the code is transpiled before the actual unit tests run. Karna runner is best used for the front-end testing i believe.
