### ISSUE TITLE
Add images to Assets?

### ISSUE THREAD

**Issue by karkkant** [reactGo/reactGo#411]
Say, if I want to do something like this to display an arbitrary icon in component:
`<img src={'/images/' + this.props.item.someType + '.png'} />`

It doesn't work out-of-the-box since the images would have to be served from /public folder. I could work around this by moving images folder to public/assets, and change build script so that bundles and rimraf would target a resource subfolder... But is there a better way to do this? If not, maybe it's something that could be enhanced in template?

**Comment by choonkending** [comment]
Thanks for raising this issue!

Is this because you are not serving the images from your server?

**Webpack**
```javascript
// If you have the images within your project
import filePath from 'path/to/image/in/your/project';

<img src={filePath} />
```

**CDN**
If you have a CDN, perhaps you could set your [publicPath](https://github.com/choonkending/react-webpack-node/blob/master/webpack/webpack.config.prod.js#L90) to be your CDN path

If your image server is different from static assets, perhaps use an absolute path?

@psimyn is the resident webpack guru, so he can correct me if I'm wrong :)

**Comment by jrodl3r** [comment]
BTW, using SVG Symbols (Sprites) totally works right out-the-box... And it's awesome 👍 
```javascript
import logos from 'images/logos.svg';
// ...
return (
  <svg>
    <use xlinkHref={logos + '#' + team.id}></use>
  </svg>
);
```

ex: [css-tricks.com/creating-svg-icon-system-react](css-tricks.com/creating-svg-icon-system-react)

**Comment by felizuno** [comment]
While I like this solution (setting src to the image data) for images with no retina requirements, I'm struggling with how to use the above syntax with `srcSet` to provide a 2x image source. Is this possible, or do I need images in `/assets` to make this work?

**Comment by donpinkus** [comment]
Does this mean you need to explicitly "import" each image in your project? What about pages with dynamic images (e.g. loading a profile picture based on a URL param)?

**Comment by psimyn** [comment]
@donpinkus, setting src to an `import`ed file is only needed for static assets, and images that live with your code. You can still set src to be any image path any it will work fine.

e.g.

```
 <img src={this.props.profileImageUrl} />
```

@felizuno the data URL is set in [webpack config](https://github.com/reactGo/reactGo/blob/master/webpack/webpack.config.prod.js#L37) - removing this line will mean you always get image URLs so can use with srcSet

@karkkant for your issue - so you want to serve images from the `somedomain.com/images` ? If you have them in that folder already you could set express to resolve that path and I think it should work. Otherwise I've used [webpack copy plugin](https://www.npmjs.com/package/copy-webpack-plugin) for images, which means you don't need to change rimraf (would copy the images from some path to static/assets as part of the build)

**Comment by mnoleto** [comment]
I`m struggling with this problem: I have URLs from uploaded images saved on my database and I need to load this images. I`ve tried to require using variables with no success (Module not found):

```
<img src={require(path + fileName)} />
```

 When I use the same URL as a string it works.

ex:
```
<img src={require('images/upload/filename.png')} />
```

I think that my problem is related with this raised issue, but I couldn`t solve the problem.

Thanks

**Comment by psimyn** [comment]
@mnoleto do you need to use require if the images are saved at a public path? I would think you could just use strings without require.

ex:

```
<img src='/images/upload/filename.png' />
```

`require`ing images or static assets is only for those that go through the build process

**Comment by mnoleto** [comment]
@psimyn 
I`ve tried that at first, with different paths (relatives and absolute), but couldn`t  show the image. Because that I start trying with require.

Thanks for your support.

**Comment by psimyn** [comment]
it may also depend on `publicPath` from webpack config (if your images aren't served from '/' or are on a different domain). Do you have more complete example somewhere?

**Comment by mnoleto** [comment]
https://github.com/mnoleto/botecofc

The component that try to load this images:
https://github.com/mnoleto/botecofc/blob/master/app/components/admin/UploadImage.jsx
Line 142

I`m developing this component to upload images using react-dropzone and show them later.

The webpack config files are the same of reactGo repo.

Thanks

**Comment by psimyn** [comment]
might need to play around with the server config possibly express.static is stealing the requests and only trying to serve images out of 'public' folder

https://github.com/mnoleto/botecofc/blob/master/server/config/express.js#L43

You can add a second express.static line to serve images from `./app/images/uploads` or some other path

**Comment by mnoleto** [comment]
@psimyn You save my day. I added this line and everything worked.

`app.use('/images', express.static(path.join(__dirname, '../..', 'app', 'images')));`

I was definitely looking at the worng direction. 
Thank you very much.

**Comment by psimyn** [comment]
@karkkant does `express.static` work for you as well? 

I'm not sure if we would want to add `/images' route by default, but could be worth adding readme or something about this.

**Comment by montezume** [comment]
I ended up using CopyWebpackPlugin to copy my assets and then used them.

https://www.npmjs.com/package/copy-webpack-plugin
