### ISSUE TITLE
Secure / Encrypt Fetched-Data

### ISSUE THREAD

**Issue by jrodl3r** [reactGo/reactGo#418]
Seeking solution for securing/encrypting fetched-data.

even after enabling HTTPS, all fetched-data is still raw-accessible in the console as _{'human-readable': 'response-data'}_.

Ideally, fetched-JSON response would arrive via https protocol, encrypted to keep from peering eyes.

**Comment by choonkending** [comment]
Not an expert in this area, but definitely a fan of improving our security.

Do you want a

```
Encrypt in browser -> Decrypt in server

Encrypt in server -> Decrypt in browser
```

sort of model? I have 0% knowledge in this, but we could work to find out what a good way of doing this is.

**On a side node**
We should add helmet into our express to improve security.

**References**
[Security best practices](https://expressjs.com/en/advanced/best-practice-security.html)

**Comment by ZeroCho** [comment]
I'm running a blog based on reactGo, and I think we need to add data-encryption and prioritize it because initial data is shown to everyone who knows how to use browser console.

For example, my blog has a problem that members' emails are scraped by search engine and robots. This is not what my members want.

One more thing. I added helmet into my blog and it works well. Helmet protects from various threats and it's very simple to use.
`app.use(helmet());`

**Comment by choonkending** [comment]
Agree with both your points. We should priority security as well as performance.

- [ ] https://github.com/reactGo/reactGo/issues/119 Do you wanna create helmet as a PR?
- [ ] Data encryption

I'm not sure what data encryption approaches we should take, do you have any ideas? I'll need to start researching on ways to handle this.

**Comment by ZeroCho** [comment]
@choonkending #429 here is PR

**Comment by jrodl3r** [comment]
Very cool adding helmet 👍 

@choonkending We should definitely add the _option_ to `[ Encrypt-on-Server » Decrypt-on-Client ]` (emphasize _optional_ because most wont need encryption). However, I'm not sure if the async-POST-data is being encrypted as it's sent from the client to the server... I will have to inspect this more and confirm - unless @ZeroCho beats me to it ; ) 🍺

**Comment by choonkending** [comment]
Good work guys! I might have to handball this to @jrodl3r and @ZeroCho (and whoever is interested) as I'm focused on improving offline support and performance for this and next week!

**Comment by jrodl3r** [comment]
@ZeroCho i'm experimenting with a few simple object encryption pkg's, but the problem i'm having right now is that Fetch (promise) doesn't have _success / failure_ handlers to run `decrypt()` before calling the reducer...

And I'm pretty sure we can't be doing stuff like that in the reducers anyways (I still tried, it didn't work either)...

**Comment by ZeroCho** [comment]
@jrodl3r How about decrypting inside the reducer? Like `const decryptedResult = decrypt(action.result);`

**Comment by jrodl3r** [comment]
@ZeroCho is that really the right place to be doing that? I'm not 100% sure about that.

I tried it anyway, doesn't work on the client/browser, but it does on the server =(

**Comment by ZeroCho** [comment]
This is what I think we need to do for encryption.

- The data is stored encrypted on the server.
- It was encrypted using a public key.
- The server sends the encrypted to the client.
- The client needs to decrypt it using their local private key.

The thing is, how we can get local private key securely.

By the way, I think we need to encrypt and decrypt window.__INITIAL_STATE__ only, because we already use SSL(https) and get/post requests are handled via https.

**Comment by jrodl3r** [comment]
that sounds pretty good. I would think `process.ENV` for the private key, eh? Heroku config on Prod, git-ignored local secret on Dev?

I completely agree about `window.INITIAL_STATE` ...it creeps me out that the whole app state is just hanging out there like that in view-source =\

As for SSL, even when it's configured, enabled and accessed + confirmed via HTTPS:// ...the Fetched Object Data is unencrypted, totally raw. This was the initial reported issue.

**Comment by ZeroCho** [comment]
We need to find the encryption & decryption package which can be used in both client and server.

**Comment by ZeroCho** [comment]
@jrodl3r [CryptoJS](https://www.npmjs.com/package/crypto-js)

**Comment by jrodl3r** [comment]
I kept hitting the wall w/ CryptoJS errors, but if you can get it working that'd be dope ; )

**Comment by ZeroCho** [comment]
I almost made it, but one thing stops me.
How can I send process.env.DECRYPT_KEY from server to client.jsx?

**Comment by ZeroCho** [comment]
I concluded that I can't make perfectly secure data transfer process. We should rely on SSL. But I could make temporary measure which blocks robots from scraping initial state, by encrypting with public key on the server and decrypting with public key on the client. Because this uses the PUBLIC key, it doesn't protect someone from decrypting manually, but no more raw initial state on html.

**Comment by ZeroCho** [comment]
![encryption](https://cloud.githubusercontent.com/assets/10962668/18101404/9526f190-6f29-11e6-9a26-76f4f1ce1cc5.png)
Its encrypted like this.
But I'm not sure how much this will affect performance such as initial loading.

**Comment by jrodl3r** [comment]
@ZeroCho can definitely settle for "easily decrypt-able, but not human-readable" - can't wait to see what you came up with! 🍻

**Comment by ZeroCho** [comment]
I now have some time to make PR. I will make PR this weekend

**Comment by slavab89** [comment]
So my 2 cents on this and lets decide how to proceed with this.
Regarding sending data client -> server.
When using HTTPS, it would take care of the encryption for you.
When you are on the browser, there is no reason that you wont be able to see what you send in the developer tools, its you who are making the requests therefore there is no reason to hide this data.
If you would put a "sniffer" like `fiddler` or `wireshark` or something similar then you should not be able to see the data inside the request since its enrypted due to the HTTPS.

Regarding the initial fetched data being shown, is it that bad? I mean even if you encrypt it on the server and then decrypt it on the client, it is possibly accessible on the client side somehow (through the redux store and what not).
Moreover, if you just dont want it to be humanly readable then its possible to just do simple symmetric hashing. In case the data should really be encrypted then it should not be possible to decrypt it on the client side (also not really usable on the client side - similar to a session id cookie).

**Comment by choonkending** [comment]
Can you just delete it just once initialise your store? Maybe that way
might be slightly safer without the overhead of encrypting and decrypting

**Comment by GGAlanSmithee** [comment]
Generally, I tend to agree with @slavab89 on this topic. There really isn't any notion of secure data in the client. Just the same way you can inspect password field data etc. you can inspect any other "hidden" data in the dev console, such as cookies, local storage etc etc.

Any measure taken would IMO only provide a false sense of security, or end up creating a useless client, with non-readable data etc. It might be possible to do _something_ but I have a fealing it would come at a high cost.

I think @ZeroCho summarized it well

> I concluded that I can't make perfectly secure data transfer process. We should rely on SSL. But I could make a temporary thing which blocks robots from scraping initial state, by encrypting with public key on the server and decrypting with public key on the client. Because this uses the PUBLIC key, it doesn't protect someone from decrypting manually, but no more raw initial state on html.

But, this is, IMO, worse than no protection, since it is in fact, no protection.

@choonkending don't w ealready [do that](https://github.com/reactGo/reactGo/blob/master/app/client.jsx#L30)?
