### ISSUE TITLE
Can we integrate fecth-data and pages?

### ISSUE THREAD

**Issue by ZeroCho** [reactGo/reactGo#689]
### Description
- Type: Enhancement

## Enhancement

**Reason to enhance/problem with existing solution**
Just my opinion. I am very satisfied with recent update on head meta. By the way, can we integrate fetch-data and pages into one? 

**Suggested enhancement**
I think we can handle fetch-data in pages folder

**Pros**
This makes folder structure simple.

**Cons**
I don't know, haha...

**Comment by ZeroCho** [comment]
I'll test it on my fork and tell you whether it is good or not

**Comment by choonkending** [comment]
> I am very satisfied with recent update on head meta

Thanks!! I really appreciate that! I put a lot of thought into it. Hopefully it's a solution that's easy to use!

Do you mean moving the `fetch-data` folder into `pages/` or making the fetch-data on componentDidMount on a page?

I think it might make the folder structure simpler, but the way i see it is:
- `pages/` handles page specific things, `meta` tags etc
- `fetch-data` is handled at a Route level, although they are the same, `data-fetching` seems to me a route-level, `Page` to me is more a View rather than a route. By coupling the data-fetching to the view, it might make things harder to change in the future?

Let me know if the above makes sense/if you disagree!

**Comment by ZeroCho** [comment]
I agree with you. After testing on my blog, I found out that fetch-data cannot be handled in pages.
