### ISSUE TITLE
PM2 or Forever

### ISSUE THREAD

**Issue by ZeroCho** [reactGo/reactGo#704]
### Description
- Type: Enhancement

## Enhancement

**Reason to enhance/problem with existing solution**
When server down due to error, auto restart needed. I don't know PM2 or Forever well, but I heard that it's useful for production environment.

**Suggested enhancement**
Start app with PM2 or Forever

**Pros**
Don't need to worry server down.

**Cons**
Maybe need to restructure server.

**Comment by choonkending** [comment]
I've used PM2 awhile ago, and it seemed like a pretty good use! Do you want to try it out?

**Comment by JCMais** [comment]
For PM2, an ``ecosystem.json`` could be added to the project. http://pm2.keymetrics.io/docs/usage/deployment/

I don't know about Forever, stopped using it many moons ago.

**Comment by ZeroCho** [comment]
@JCMais Thank you. I don't know server well. What do you mean by **stateless**?

**Comment by JCMais** [comment]
@ZeroCho it should not store data in their own process, like client sessions for example. A chat app for example, you should store the current connected clients, or current chatrooms, inside an array, otherwise it would be invisible to the other instances running. A shared memory should be used in this case, like Redis.

**Comment by ZeroCho** [comment]
After some search, I found that PM2 can be redundant when using with Heroku.
