### ISSUE TITLE
Port for KOA

### ISSUE THREAD

**Issue by jeremyjs** [reactGo/reactGo#718]
### Description
- Type: Question

---------------------------------------------------------------
## Question

I'm interested in forking this boilerplate to use koa.js instead of express. Does that already exist somewhere? If not, what's the best way to get started doing that? i.e. which packages are related to koa? Is anyone else interested in this?

**Comment by slavab89** [comment]
We're cleaning up the project and trying to close issues.
This issue is pretty old and you probably already solved it 😄 but in any case, the switch from express to koa shouldnt be to difficult as the changes are only on the server side
If you still have an issue, please comment here or open a new one.
