### ISSUE TITLE
Spike React Router v 4 - the API is looking amazing.

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#827]
# Why

Explore RR4 - it's API might simplify our code + give us more control.

https://reacttraining.com/react-router/

**Comment by GGAlanSmithee** [comment]
This would be super nice! Allow me to share my experience when I attempted to move to rr4 in a project built on this boilerplate. The problems I faced was.

1. The lack of code splitting hooks.
2. Troubles getting HMR to work

For point 2, I am pretty sure it was just some error on my part (didn't really try that much), because there are HMR examples out there for rr4, but for point 1 there was, for me, no acceptable solution at the time (~1 month ago). In rr2/rr3, one would use `getComponent`, but there is no equivalent in rr4. There are user-space solutions to this, but it comes with the additional baggage of maintenance etc, so I chosed to not port at that point.

**Comment by zamiang** [comment]
Just came across this blog post on some of the challenges (and solutions!) for SSR in RR4. Might be of some use: https://ebaytech.berlin/universal-web-apps-with-react-router-4-15002bb30ccb#.ttmt1msh0

**Comment by ZeroCho** [comment]
react-router@4 and react-router-redux@5 is out (react-router-redux is @5.0.0-alpha not though) but documentation of react-router@4 is not complete yet.
If it is complete and official version of react-router-redux@5 comes out, I'll try to update this repository to react-router@4

**Comment by gudh** [comment]
@ZeroCho How about replace react-router-redux (which is still in alpha) with [connected-react-router](https://github.com/supasate/connected-react-router) ? Because there isn't a roadmap for react-router-redux, a month past, and it's still in alpha 

You can change it back react-router-redux once a  stable version is released.

**Comment by ZeroCho** [comment]
okay i'll give it a try

2017. 4. 14. 오전 11:56에 "gudh" <notifications@github.com>님이 작성:

**Comment by ZeroCho** [comment]
@gudh Hmm. `Connected-react-router` seems it does not support SSR.

**Comment by kybarg** [comment]
@ZeroCho on server side use `<StaticRouter>`

**Comment by choonkending** [comment]
I heard good stuff about rr4. Hehe. If react router redux doesn't support
it, I suggest we remove it as a dependency altogether!!

**Comment by ZeroCho** [comment]
@kybarg I know. But StaticRouter is just for SSR. We also wanted to split code, which is the toughest part. Even react router team themselves gave up...

**Comment by ZeroCho** [comment]
#978
