### ISSUE TITLE
Using react-select

### ISSUE THREAD

**Issue by todoesverso** [reactGo/reactGo#833]
### Description
- Type:  Question

## Question

**How to use react-select style in reactGo?**

According to react-select [documentation] (https://github.com/JedWatson/react-select) I should only do 
`import 'react-select/dist/react-select.css';`

To import the style but the component ends up with no style.

What am I  missing?

**Comment by todoesverso** [comment]
`import '!style-loader!css-loader!react-select/dist/react-select.css';`

Did the trick! :)

**Comment by slavab89** [comment]
Yeah its doing the trick for me but i dont think thats the actual good solution because then you are not really able to change anything regarding the styling - if you need =]
You are basically canceling the css loaders on that. 
I want to know how you are able to still use them - having hard time figuring it out as well =[[

I mainly need this because of: https://github.com/callemall/material-ui/issues/4952#issuecomment-273823982

**Comment by Cleanshooter** [comment]
I would just do like you are trying to do and add a special handling to your webpack config.

webpack/rules/index.js
   ```javascript
    javascript({ production, browser }),
    css({ production, browser }),
    image(),
    {
    	test: /\.css$/,
	    use: [
	    	browser ? "style-loader" : "isomorphic-style-loader",
	    	browser ? "css-loader" : "css-loader/locals"
	    ],
	    include: PATHS.modules +"/react-select/"
    }
```

You'll have to install the "isomorphic-style-loader" library... if you need it... I did for mine.

**Comment by slavab89** [comment]
@Cleanshooter Thanks, this works but it leaves all classnames the same as the original. If i want to override some of them, how should i do this?

**Comment by Cleanshooter** [comment]
@slavab89 you could fork the repo and change it that way... I do that more than I should probably 😜

I guess I'm not sure what you mean to accomplish by overriding some of them...

**Comment by slavab89** [comment]
Mostly to change the design. As you can see https://github.com/callemall/material-ui/issues/4952#issuecomment-273823982, he posted a css that makes it look more "materialized".
In any case, for now i think i'll just stick with what i did and that is to copy the whole react-select css, change what i need and load that css instead of the regular one from the module itself.

**Comment by slavab89** [comment]
We're trying to clean up the project and close issues.
The original issue was resolved even though the solution was not perfect.

I ended up using the solution that was originally posted :)
