### ISSUE TITLE
External css file

### ISSUE THREAD

**Issue by mbinet** [reactGo/reactGo#838]
## Question

Hi,

I don't get how to import simple css files from Boostrap for example as there is no index.html in the project.
Also, a lot of simple react libraries don't work with reactGo because they can't find there css (they work fine in another React project) like ant design or react-html5-video

**Comment by metallica666** [comment]
HI @mbinet I think you can user bootstrap as a module (npm install bootstrap --save). I hope helps you.

**Comment by Cleanshooter** [comment]
This is because reactGo started using CSS Modules... perhaps a bit prematurely.  I've run into several issues with other libraries for the exact same reason.  The index.html is built with react-helmet so if you want you can put static stuff in there I guess... check the server/renderer/pageRenderer.js

**Comment by mbinet** [comment]
Thanks @Cleanshooter ! I managed to put static content in there :)
