### ISSUE TITLE
Question - How to disable server side rendering during development?

### ISSUE THREAD

**Issue by getshao** [reactGo/reactGo#840]
### Description
- Type: Question

## Question

**How to disable server side rendering during development?**
I would like to introduce a flag to disable server side rendering during development. I suspect it would make debugging with Webstorm much easier

Hints on where to start?

**Comment by Cleanshooter** [comment]
This is a universal boilerplate so... if you don't render on the server you don't get an application... Universal is a methodology... it'd pretty difficult to turn it off and still have anything work...  because there would be no page... NODEMON is only monitoring certain directories so only certain changes should cause a server compilation anyway.  

If you don't want the server to reload when you make changes in these files: 
      "app/utils",
      "app/routes.jsx",
      "server",
      "webpack"

You could remove nodemon from the dev command in the package.json scripts section 
`"dev": "cross-env NODE_ENV=development nodemon",`
change to 
`"dev": "cross-env NODE_ENV=development",`

I don't necessarily think this is a good idea but it might help you... you could always use a different IDE.  I live in Sublime myself and never have any issues.

**Comment by GGAlanSmithee** [comment]
@Cleanshooter I interpret the request as wanting to serve a static index.html page and only render the application on the client, which should be trivial.

@getshao, if you want to use a flag:

1. Add a node ENV to the dev script, STATIC or w/e
2. Create a static HTML file which includes your application (client) script
3. In the server, conditionally render the application (like now, using the render middleware) or just serve the static HTML file

Having said that, I have a hard time seeing the benefits of this. Let me know if you need more pointers.

**Comment by getshao** [comment]
Thanks guys. I end up doing something similar to @GGAlanSmithee mentioned.

The purpose is now I am able to use debugger for server side node.js code, try it yourself. It is incredible difficult when server side rendering is enabled.

Here is the dev.pug file
`
doctype html
html
  head
    title(data-react-helmet='true') reactGo - just ship it
body
  #app
  script.
    window.__INITIAL_STATE__ = {"isFetching":false,"topic":{"topics":[],"newTopic":""},"repo":{},"user":{"authenticated":false,"isWaiting":false,"message":"","isLogin":true},"message":{"message":"","type":"SUCCESS"},"routing":{"locationBeforeTransitions":null}}
  script(type='text/javascript', charset='utf-8', src='/assets/app.js')
`

and here is the logic inside `render/middleware.js`
`
export default function render(req, res) {
  const enableServerSideRendering = true;
  if (!enableServerSideRendering) {
    return res.render('dev');
  }
...
`
