### ISSUE TITLE
Investigate JWT

### ISSUE THREAD

**Issue by choonkending** [reactGo/reactGo#861]
# Background
Raised in https://github.com/reactGo/reactGo/pull/853#issuecomment-295668648

We should investigate whether it makes sense to rely on [JSON web tokens](https://jwt.io/) to integrate into our repository.

**Comment by slavab89** [comment]
I guess it kinda depends on what you actually need from your app.
When using passport, you usually use a session as well in order to keep track of of user and his data.
When using JWT you pretty much do the same thing, only that the whole user data that you need sits inside the token itself.

The reason that people often use JWT is when they dont have / dont want a server side. Why? because when using JWT you dont need a session store, everything you need is on the token already. That is great because you can scale your application pretty easily - just spread it across servers without the need for a shared session storage.
A drawback to this is that as long as a user has the JWT, he has access to the system. This means that if this token is somehow stolen, then the thief will have access to the system. This means that if you want to revoke access to the user, you wont really be able to do that until the token expires. This is because you dont keep track of your issues tokes anywhere.

To fix those kind of "problems" of JWT, projects often start using OAuth2 or OpenID Connect (which is what i did). Or do some kind of mix between sessions and JWT by using JWT refresh tokens.

It possible to play quite a lot with all of those logics but i am not sure if this project is actually the place for this, maybe in a different branch from the main?
The main reason for me saying this is that in a "real world" you would probably write a different server that handles all the token related stuff - creating, verifying, refreshing etc.

**Comment by ZeroCho** [comment]
@choonkending Are you planning to separate API server and static content server?

**Comment by choonkending** [comment]
@slavab89 Thanks for the explanation!

Very valid concerns, and to be honest I have not considered it as far as having a hybrid OAuth2 and JWT session.

> The main reason for me saying this is that in a "real world" you would probably write a different server that handles all the token related stuff - creating, verifying, refreshing etc.

In my mind, I would like us moving towards that architecture. And to answer @ZeroCho 's question, yes I am planning to separate the API server and the static content server (which renders our app).

If we could separate bits of system to do **one thing well with well-defined interfaces**, I think it would allow reactGo to be way more configurable. Perhaps the JWT spike would involve us writing another small service separate from our server that handles token related stuff well. I do not know the effort involved in that and would definitely value everyone's input.

In the future, I could then experiment writing API servers with Haskell 🚀 haha!

**Comment by slavab89** [comment]
Sound cool 👍 

Regarding the JWT token handling. It is possible to do something simple like what @ZeroCho showed in the other ticket - where they use express-jwt middleware to handle this.
What i actually meant to say regarding the "real world" was that if you have some additional API servers, you would want to implement JWT validation there as well, so either you do the same handling with express-jwt like you would here or you will have a different server/service that handles that logic for everyone.

For starters i think you might be right in going the path of writing another small service. For now maybe it can be just another file that handles that stuff, and if anyone wants/needs he can create a different server out of it.

**Comment by choonkending** [comment]
Did a bit more reading + research + thinking around JWTs in general. [**Stop using jwt for sessions**](http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/) made a lot of sense for me.

One selling point that initially appealed to me was that we could make our REST APIs  **stateless**. Not having to rely on sessions as we no longer need to persist any information in memory (not in the database). 

Most of the drawbacks/concerns about jwt (e.g. having your token stolen) have an ~_okay_ solution (having shorter expiry times).

However, the normal recommended approach (i.e. save your tokens in localStorage) **does not really make sense** in our Server-side rendering context. When a user is currently still logged in and makes a full page refresh, we want to render the authorised content for him/her. We cannot pass the token in the Header from localStorage if it's just a full page refresh. 

We need cookies in this case. I think we can attempt to use cookies + jwt to make things work. Seems like extra complexity on the client side to be honest. 

We can still consider:
- Separating our an auth service for logging in, signing up on the client
- If we still want jwts, having an authentication service on the backend that handles what token creation, refreshing, etc as @slavab89 mentioned

For now, I'd like to park this aside. My one true goal is to ultimately separate the static content server + rendering logic into a beautiful service, decoupled from the API server.
