### ISSUE TITLE
Redirect After Login / Sign Up

### ISSUE THREAD

**Issue by jrodl3r** [reactGo/reactGo#881]
Not having any luck tracking down where the redirect takes place after a successful login / sign up. Anybody know where that is set? Looking to send users to `/account` instead of `/` on login + sign up.

Thx!

**Comment by choonkending** [comment]
Look at the action creator for user, in manual login we use react router redux to push a new path. (Maybe not an ideal solution )

**Comment by jrodl3r** [comment]
Ah... So we just change `dispatch(push('/'));` to `dispatch(push('/account'));`

That works fine for me... Thx!

**Comment by GGAlanSmithee** [comment]
I would just like to add that I used to do it like so, but ended up doing `window.location.replace(state.from)`, in order to avoid situations where the redux state wasn't cleared of all protected info. It is certainly possible to do it client side only, but for me the hard reload is worth it since it reduces complexity and hopefully a user isn't logging in / out too often.
