### ISSUE TITLE
Populate User State After Authentication

### ISSUE THREAD

**Issue by jrodl3r** [reactGo/reactGo#888]
What is the suggested method for loading user data (ex: `email`, `fname`) after a successful login?

Should it be fetched after POST, or should the controller pass an object back on successful `passport.authenticate(...)`?

Thx 👍

**Comment by slavab89** [comment]
I would say that after a successful login `passport.authenticate` you should redirect to your home page.
When that happens, it would trigger an SSR in [middleware.js](https://github.com/reactGo/reactGo/blob/master/server/render/middleware.js#L16) where the creation of a new store would happen.
As you can see there, the user details are initialized so if `req.isAuthenticated()` returns true, you can grab the user details that you've saved on the session by using `req.user` and save them / or some of them in the store

**Comment by jrodl3r** [comment]
Thanks for the tip @slavab89, but one thing I don't understand is why anyone would ever redirect a user to the home page after a successful login? I can't recall any site that has ever done that before, because they all send to your /account page as a logged-in user typically.

**Comment by jrodl3r** [comment]
@choonkending @psimyn what do you suggest for fetching and persisting user data securely on/after login? Is this possible right now?

**Comment by slavab89** [comment]
I'm doing the following: (For some reason its not really documented in passport docs)
```js
    app.get('/auth/callback',
      passport.authenticate('oidc', { failWithError: true }),
      (req, res) => {
        res.redirect('/');
      },
      (err, req, res, next) => { // Special specific error callback for that route
        res.redirect('/?loginError=' + encodeURIComponent(err));
      }
    );
```

But it should work with the current code that's in the branch.

And in middleware.js
```js
  const store = configureStore({
    user: {
      authenticated,
      userData: req.user,
      ......
    },
    ......
  }, history);
```

It should trigger a SSR request because you force the user to do a redirect to your home page. You could add a print in `middleware.js` to see if it actually reaches there...

**Comment by ZeroCho** [comment]
I populate them in `deserialize` function like below
export function deserializeUser (id, done) => {
  User.findById(id).populate('friendRequest friends').exec((err, user) => {
    done(err, user);
  });
};

**Comment by jrodl3r** [comment]
You guys are awesome, really appreciate the help on this! Feels so close to working... However, still coming up empty handed on both options...

@slavab89 I'm only using 'local' passport login setup (google login is disabled). Using the latest on master, and that first part looks pretty unique. I get the `middleware.js` part, but the other part has me pretty confused as to what I'd change on the latest build to get this user-state-population-on-login working =\

@ZeroCho How would I modify the [latest (master)](https://github.com/reactGo/reactGo/blob/master/server/db/mongo/passport/deserializeUser.js) `deserializeUser()` to populate `user.profile` state?

```javascript
export default (id, done) => {
  User.findById(id, (err, user) => {
    done(err, user);
  });
};
```

Thx!

**Comment by ZeroCho** [comment]
In ReactGo case, you can use user.profile without doing anything.

**Comment by jrodl3r** [comment]
@ZeroCho what?

**Comment by ZeroCho** [comment]
```
const UserSchema = new mongoose.Schema({
  email: { type: String, unique: true, lowercase: true },
  password: String,
  tokens: Array,
  profile: {
    name: { type: String, default: '' },
    gender: { type: String, default: '' },
    location: { type: String, default: '' },
    website: { type: String, default: '' },
    picture: { type: String, default: '' }
  },
  resetPasswordToken: String,
  resetPasswordExpires: Date,
  google: {}
});
```
Current user schema looks like this.
What about email, password, tokens? Do they come to `user` object? If so, there's no reason that `profile` object doesn't come to `user.profile`

**Comment by slavab89** [comment]
If you're using mongo (which seems like you do 😄 ) Then ReactGo is configured to work with a mongo DB store.
The flow of passport is basically:
1. Go to login route - Your local login route.
2. Verify the use info [here](https://github.com/reactGo/reactGo/blob/master/server/db/mongo/passport/local.js)
3. If the user is a match, [serialize](https://github.com/reactGo/reactGo/blob/master/server/init/passport/index.js#L18) it. It will save the use ID in the DB.
4. Handle success callback (redirect to home)
5. A new request should come to the server. Before reaching middleware.js it should [deserialize](https://github.com/reactGo/reactGo/blob/master/server/init/passport/index.js#L22) the user using the [local passport config](https://github.com/reactGo/reactGo/blob/master/server/db/mongo/passport/deserializeUser.js). It should fetch the user based on the ID that was saved in the session.
6. Should get to `middleware.js` and create the store correctly with filled `req.user` object. (You can also see `req.session` for the full session data)

I hope that i'm correct with that flow 😜 .
Try adding a console.log print in both `serializeUser` and `serializeUser` to see what info you get there. Or console.log in another points to see that everything is corrected.

**Comment by jrodl3r** [comment]
@slavab89 @ZeroCho take a look at this: [github.com/jrodl3r/reactGoUserDataPop/commit/...](https://github.com/jrodl3r/reactGoUserDataPop/commit/713e6d43b5f027a12b4e8b66b44ffb9513b8146c)

When I login the `profile.email` appears because it's handled w/ reducer, but the `profile.refCode` never arrives/updates. Also, after a refresh they both revert to empty strings.

What am I doing wrong? How am I breaking this? It did work initially... 😠

**Comment by slavab89** [comment]
So it actually something "wrong" with the manual login (We should have payed more attention to it 😄 )
When you perform a manual login (using `local` strategy) it behaves a little different than what we've described before.

You send a [request from the web page using Axios](https://github.com/reactGo/reactGo/blob/master/app/actions/users.js#L58) to the server with the user details to perform a login
You get to the [login endpoint](https://github.com/reactGo/reactGo/blob/master/server/db/mongo/controllers/users.js#L7) on the server. That checks the user details and if everything is correct, it returns a 200 status.
The action that you've previously sent gets a response back, and does `dispatch(push('/dashboard'));`. This triggers a CLIENT-SIDE redirect, meaning only the web site changes, it doesnt go to the backend for this. So you dont get the user details like you've done in `middleware.js`

When using a manual login, i see 3 options that can be done (We might actually want to change ReactGo logic as well for this)
1. Force a page refresh - to get to the SSR render - by changing `dispatch(push('/dashboard'));` to `window.location = '/dashboard`
2. Return the user data (Only what's needed) from the [manual login endpoint](https://github.com/reactGo/reactGo/blob/master/server/db/mongo/controllers/users.js#L18) back to the web page and trigger and dispatch action to update the store with the received data (Same for signup)
3. After a successful login, send another request to get the user data.

I think the optimal choice for manual login is (2) because it wont cause a refresh of the page so the user will have a more smooth experience.
When using google login, however, its not possible to have something like this because the flow redirects you to Google site itself, so either way you're leaving the page.

**Comment by jrodl3r** [comment]
Very interesting... Considering how much of the codebase is devoted to the `user`, I'd think this functionality (simple user data population) and a basic UI on say `/dashboard` should be considered for addition to the project.

**Comment by slavab89** [comment]
Should we close this then?
btw, i've tried to write you and email (Based on your github profile) but seems like that address does not exist
