### ISSUE TITLE
Authentication Not Working on Mobile

### ISSUE THREAD

**Issue by jrodl3r** [reactGo/reactGo#890]
Happening on both Android/Chrome and iPhone/Safari.

<img width="1032" alt="screen shot 2017-05-30 at 1 05 01 pm" src="https://cloud.githubusercontent.com/assets/869411/26602552/b57c7272-4538-11e7-9d59-7368b0024dde.png">

**Comment by ZeroCho** [comment]
Did you tried in your local environment? Or reactGo Demo page?

**Comment by jrodl3r** [comment]
the [demo page](https://demo-reactgo.herokuapp.com/login)

**Comment by jrodl3r** [comment]
The user email + password are valid going into the `manualLogin()` action, and still appears good once it gets to `services/authentication.js` at `return client.request({...})`. However, the POST on `/login` seems to fail and the user login (or signUp) controller never gets called. After that, `manualLogin(data)` catches this error:

<img width="670" alt="screen shot 2017-05-31 at 3 59 53 pm" src="https://cloud.githubusercontent.com/assets/869411/26657675/3c6da418-461a-11e7-9093-b65e7fd0aeed.png">

cc @ZeroCho @psimyn @choonkending

**Comment by slavab89** [comment]
Could you take a look at the network tab in the developer tools? Find the failing request and see the response written there.
My guess is that it tells you some message about CORS (Cross-Origin Resource Sharing).
Basically it happens when you're trying to make a request from domain X to domain Y but domain Y does not allow request from domains other than himself.
If this is the case, then the simplest solution is to just allow CORS for everyone =] (use `express-cors`)

**Comment by jrodl3r** [comment]
@slavab89 Didn't get the CORS error, but you're right (as usual 👍).

So, on local-DEV, `localhost:3000` works, but  `10.0.1.3:3000` doesn't... Which is going to be a problem for anyone doing remote or mobile device debugging.

The bigger issue is that this same problem arrises in PROD when you have apex domain setup ("http://foo.com") and then mr. user hits the site using "www" (ex: "http://www.foo.com") and then boom... (side-note: This was actually the problem all along - mobile browsers will typically tack on the "www." if you just type in the apex domain, but it masks it visually so that you can't see it unless you tap the url bar to edit...)

Any way to fix this? Should the `apiEndpoint` always be "www" in `config/app.js`?

```javascript
export const apiEndpoint = isDebug ? 'http://localhost:3000' : 'https://foo.com';
```
Thx!

**Comment by slavab89** [comment]
Adding `express-cors` before the actual routes did not help? For me it did the trick 😞 

Regarding your other solution, i am a bit surprised that mobile browsers add `www` prefix to the domain name. I did not know that and it seems quite strange even.
On our production system we had to explicitly define our domain to go to the same server endpoint both on `example.com` and `www.example.com` and if a user comes through just the domain name, we would redirect him to `www` prefix.
Regarding the API endpoint in production, we've put `www.example.com` so that `axios` would access that address and not something else.
