### ISSUE TITLE
Authenticated after refresh

### ISSUE THREAD

**Issue by kennrll18** [reactGo/reactGo#909]
How is the reducer keeping it's state, after refreshing the page? I checked through out the code and I'm not seeing how it's being saved.

**Comment by slavab89** [comment]
You need to distinguish between a full page refresh and a client-side "refresh".

When you do a full page refresh - like when you enter the site from a new tab or hit F5 then the redux state is recreated. It takes the state from the server side (for example, the user), and starts to manage the state from that point. So if you have reducers running at this point (Fetching data or whatever) then the state will be updated accordingly.

When you do a client-side "refresh", its not a real refresh but rather a transition. This happens with the help of react-router and the "supporting modules" (All possible word combinations of react, router and redux 😄 ). So basically when you go to some other page, you dont go to the server and ask for the whole HTML from the start, you stay in the browser so the state is still there.

**Comment by kennrll18** [comment]
How is it getting the state from the server side? I'm using passport, redux, react and everytime i do a full page refresh, the states are gone and i have to log back in.

**Comment by slavab89** [comment]
This is happening in [middleware.js](https://github.com/reactGo/reactGo/blob/master/server/render/middleware.js#L16). As you can see, a new store is created with a `initialState` with the user. As you can see, it put the authenticated prop based on `req.isAuthenticated()` which is something that passport exposes when a logged in user session is created.

Once the store is created it is being used to run all the server side reducers. They change the store and once they finish running, the final HTML that will be sent to the user is built. As part of that, we [save the state or redux store in __INITIAL_STATE__](https://github.com/reactGo/reactGo/blob/master/server/render/pageRenderer.jsx#L27).

Once you reach to the client side, the [client.jsx](https://github.com/reactGo/reactGo/blob/master/app/client.jsx#L13) is triggered where we take the __INITIAL_STATE and use it to create the client side store - which contains the `authenticated` prop

**Comment by kennrll18** [comment]
Oh this is pretty cool. Does this mean this is server side rendering?

**Comment by slavab89** [comment]
Exactly. The server side basically prepares the initial HTML that the client should render.
This means that once the client gets this HTML, it only has to render it, it should not run a lot of code to get to the same final html. This should reduce the time until the user actually sees the page.

Of course it will not prevent stuff that happen on the client side only - like stuff that happen in `componentDidMount` (which is run only on the client side)

Please bear in mind that although this is a cool feature and usually allows performance, it does make things more difficult when developing and creating new features because you have to be aware when where and how stuff happen. For example, there is an attempt to update the react-router module to its latest version and it did not prove to be trivial as to just update the package, change a couple of lines and move on.

**Comment by slavab89** [comment]
We're trying to clean up the project and close issues.
In case you still have an issue with this, please comment here or open a new issue.
