### ISSUE TITLE
When use `npm run start` (production) after login- create new tab > we are not logined =( 

### ISSUE THREAD

**Issue by againksy** [reactGo/reactGo#931]
Hello! Found bug/problem =(
When npm run start > login> create new tab - and we are no more logined here?
The same with closing current tab and open new =( 
Maybe any one know what problem is?
Notice please, everything is OK when npm run dev (on development mode) .
Bug appears only in production

**Comment by GGAlanSmithee** [comment]
Hi @againksy 

I just tested this with [the demo app](https://demo-reactgo.herokuapp.com/) and it seems to work as expected (using the username/password login).

A few questions:
- What auth method are you using? (username/password or Google)
- What database are you using?
- What session store are you using on the server?

**Comment by againksy** [comment]
@GGAlanSmithee  , dear, on the demo app it work for me too. Can you please try locally?
I use username/password login method.
I use mongodb, 
I did not make any changes for session store, i use the default . 
Everything i had changed was the 
1- mongodb url in `server/db/mongo/constants.js`
2- and `export const apiEndpoint = 'http://localhost:3000';` in `config/app.js`  - to set local app url for production.
Noice please, everything is OK when npm run dev (on development mode) .
Thing happens only in production

**Comment by GGAlanSmithee** [comment]
I haven't been able to look at this, but since it works in development (which is using localhost) but not production, my gut feeling is that it has to do with serving the site over HTTP (not HTTPS).

This should not be the case given how to cookie is [initialized](https://github.com/reactGo/reactGo/blob/master/server/init/express.js#L64):

```js
    // If secure is set, and you access your site over HTTP, the cookie will not be set
    cookie: {
      httpOnly: true,
      secure: false,
    },
```

@againksy please confirm that you have not changed the above cookie settings.

**Comment by rihannarickeminem** [comment]
@GGAlanSmithee i didnt change cookie settings. I only changed two things:
1- mongodb url in server/db/mongo/constants.js
2- and export const apiEndpoint = 'http://localhost:3000'; in config/app.js - to set local app

**Comment by newasmod** [comment]
@GGAlanSmithee maybe you can suggest , how to fix this?

**Comment by GGAlanSmithee** [comment]
@newasmod sure, as soon as I get the possibility to investigate. Will try to find time tomorrow!

**Comment by IzaGz** [comment]
Is there any news for this bug?

**Comment by GGAlanSmithee** [comment]
Sorry. Have been very busy at work and in life.

I had some time to take a look. Everything seems to be working fine for me locally. Can you verify that you are using the correct settings in `cofig/app.js`

`export const apiEndpoint = isDebug ? 'http://localhost:3000' : 'https://demo-reactgo.herokuapp.com';`

Where you should exchange `'https://demo-reactgo.herokuapp.com'` for your own app url.

**Comment by againksy** [comment]
@GGAlanSmithee i sat the api as `export const apiEndpoint = 'http://localhost:3000'` 
so its `http://localhost:3000` for both production and development. Does it make sence?
How can i run production with local url?

**Comment by GGAlanSmithee** [comment]
@againksy I haven't debuged that, but I don't think that will work depending on your session settings. Try using the actual URL to the site.

Please try this and check back whether it works or not.

**Comment by GGAlanSmithee** [comment]
@againksy @IzaGz @rihannarickeminem is this issue resolved on your end by setting the correct `apiEndpoint`, or are  you still having problems?

**Comment by slavab89** [comment]
A bit of a strange question but between those tries do you restart your server? Maybe it crashes and restarts due to some reason?
The default session storage implemented in this project is memory so if you restart the server, all logged in sessions are removed and you need to log in once more.

Also, please verify that when you login, you have a session cookie saved in your browser for the domain of you app.

Moreover, i'm not sure how you're able to work with `apiEndpoint` set to localhost for production since the front-end (browser) wont know where to go for the actual login. It will try to go to your computer instead of the production server

**Comment by slavab89** [comment]
@againksy please check wether the latest commit that was merged fixes this issue for you.
