### ISSUE TITLE
Question: Role based access control

### ISSUE THREAD

**Issue by kkotwal94** [reactGo/reactGo#940]
Just curious how others use Postgres and implement Role based access control? I'm using this boiler plate and having a hard time thinking about how to properly do this. I'd like to think i need to manage this in react, and on entering some routes, along with api calls and their methods. Currently i have 4 tables revolving around this:
User -> UserRoles -> Roles -> RolesPriveleges -> Priveleges (where privelage === permission).

**Comment by slavab89** [comment]
You might want to consider using OpenID Connect or OAuth2 to manage all of that since it has those features and you would save time implementing that and covering it from all cases.
There are a lot of services on the internet that allow you to define all the things and control it from there.

Once you do have that in place the you would have a logged in user with some roles/privilages and that is saved on the session (for example) on the server side. On the client and react side you can save it in your redux state and take that information on different components and use it.
